<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Contoh-5.12 – Catatan 📝</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bf19b75f51ea680c8de03e84aa65eabd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Catatan 📝</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#example-5.12-from-the-book" id="toc-example-5.12-from-the-book" class="nav-link active" data-scroll-target="#example-5.12-from-the-book">📘 Example 5.12 from the Book</a></li>
  <li><a href="#contoh-5.12-perbandingan-reasuransi-antar-dua-perusahaan" id="toc-contoh-5.12-perbandingan-reasuransi-antar-dua-perusahaan" class="nav-link" data-scroll-target="#contoh-5.12-perbandingan-reasuransi-antar-dua-perusahaan">🎓 Contoh 5.12 — Perbandingan Reasuransi Antar Dua Perusahaan 🏢🏢</a>
  <ul class="collapse">
  <li><a href="#kasus-1-stop-loss-excess-of-loss" id="toc-kasus-1-stop-loss-excess-of-loss" class="nav-link" data-scroll-target="#kasus-1-stop-loss-excess-of-loss">📌 Kasus 1: Stop Loss (Excess of Loss)</a></li>
  <li><a href="#kasus-2-reasuransi-proporsional-retain-60" id="toc-kasus-2-reasuransi-proporsional-retain-60" class="nav-link" data-scroll-target="#kasus-2-reasuransi-proporsional-retain-60">🔄 Kasus 2: Reasuransi Proporsional (Retain 60%)</a></li>
  <li><a href="#kasus-3-reasuransi-proporsional-retain-50-50" id="toc-kasus-3-reasuransi-proporsional-retain-50-50" class="nav-link" data-scroll-target="#kasus-3-reasuransi-proporsional-retain-50-50">⚖️ Kasus 3: Reasuransi Proporsional (Retain 50%-50%)</a></li>
  <li><a href="#tabel-ringkasan" id="toc-tabel-ringkasan" class="nav-link" data-scroll-target="#tabel-ringkasan">📊 Tabel Ringkasan</a></li>
  </ul></li>
  <li><a href="#brainstorming-apa-pelajaran-dari-contoh-5.12" id="toc-brainstorming-apa-pelajaran-dari-contoh-5.12" class="nav-link" data-scroll-target="#brainstorming-apa-pelajaran-dari-contoh-5.12">🧠 Brainstorming — Apa Pelajaran dari Contoh 5.12?</a>
  <ul class="collapse">
  <li><a href="#mengapa-contoh-ini-penting" id="toc-mengapa-contoh-ini-penting" class="nav-link" data-scroll-target="#mengapa-contoh-ini-penting">💭 Mengapa contoh ini penting?</a></li>
  <li><a href="#apa-insight-utamanya" id="toc-apa-insight-utamanya" class="nav-link" data-scroll-target="#apa-insight-utamanya">🧮 Apa insight utamanya?</a></li>
  <li><a href="#apa-implikasi-praktisnya" id="toc-apa-implikasi-praktisnya" class="nav-link" data-scroll-target="#apa-implikasi-praktisnya">🎯 Apa implikasi praktisnya?</a></li>
  </ul></li>
  <li><a href="#penjelasan-matematis-contoh-5.12" id="toc-penjelasan-matematis-contoh-5.12" class="nav-link" data-scroll-target="#penjelasan-matematis-contoh-5.12">🏢 <strong>Penjelasan Matematis Contoh 5.12</strong></a>
  <ul class="collapse">
  <li><a href="#definisi-model-klaim" id="toc-definisi-model-klaim" class="nav-link" data-scroll-target="#definisi-model-klaim">📦 <strong>Definisi Model Klaim</strong></a></li>
  <li><a href="#kasus-1-reasuransi-stop-loss-excess-of-loss-penjabaran-rinci" id="toc-kasus-1-reasuransi-stop-loss-excess-of-loss-penjabaran-rinci" class="nav-link" data-scroll-target="#kasus-1-reasuransi-stop-loss-excess-of-loss-penjabaran-rinci">🛑 Kasus 1: Reasuransi Stop-Loss (Excess of Loss) — Penjabaran Rinci</a></li>
  </ul></li>
  <li><a href="#rincian-nilai-harapan-variansi-kasus-1-stop-loss" id="toc-rincian-nilai-harapan-variansi-kasus-1-stop-loss" class="nav-link" data-scroll-target="#rincian-nilai-harapan-variansi-kasus-1-stop-loss">📌 Rincian Nilai Harapan &amp; Variansi – Kasus 1 (Stop-Loss)</a>
  <ul class="collapse">
  <li><a href="#asumsi-dasar" id="toc-asumsi-dasar" class="nav-link" data-scroll-target="#asumsi-dasar">🧠 Asumsi Dasar:</a></li>
  <li><a href="#total-payout-perusahaan-a-dan-b" id="toc-total-payout-perusahaan-a-dan-b" class="nav-link" data-scroll-target="#total-payout-perusahaan-a-dan-b">🧾 Total Payout — Perusahaan A dan B</a></li>
  <li><a href="#catatan-penting" id="toc-catatan-penting" class="nav-link" data-scroll-target="#catatan-penting">💡 Catatan Penting:</a></li>
  <li><a href="#intuisi-sederhana" id="toc-intuisi-sederhana" class="nav-link" data-scroll-target="#intuisi-sederhana">🧠 Intuisi Sederhana:</a></li>
  <li><a href="#kesimpulan" id="toc-kesimpulan" class="nav-link" data-scroll-target="#kesimpulan">🧠 Kesimpulan:</a></li>
  <li><a href="#kasus-2-reasuransi-proporsional-60-penjabaran-rinci" id="toc-kasus-2-reasuransi-proporsional-60-penjabaran-rinci" class="nav-link" data-scroll-target="#kasus-2-reasuransi-proporsional-60-penjabaran-rinci">🔄 Kasus 2: Reasuransi Proporsional 60% — Penjabaran Rinci</a></li>
  <li><a href="#kasus-3-reasuransi-proporsional-50-penjabaran-rinci" id="toc-kasus-3-reasuransi-proporsional-50-penjabaran-rinci" class="nav-link" data-scroll-target="#kasus-3-reasuransi-proporsional-50-penjabaran-rinci">⚖️ Kasus 3: Reasuransi Proporsional 50% — Penjabaran Rinci</a></li>
  <li><a href="#catatan-penting-1" id="toc-catatan-penting-1" class="nav-link" data-scroll-target="#catatan-penting-1">💡 Catatan Penting:</a></li>
  <li><a href="#intuisi-sederhana-1" id="toc-intuisi-sederhana-1" class="nav-link" data-scroll-target="#intuisi-sederhana-1">🧠 Intuisi Sederhana:</a></li>
  <li><a href="#teorema-kunci" id="toc-teorema-kunci" class="nav-link" data-scroll-target="#teorema-kunci">📜 <strong>Teorema Kunci</strong></a></li>
  <li><a href="#tabel-ringkasan-hasil" id="toc-tabel-ringkasan-hasil" class="nav-link" data-scroll-target="#tabel-ringkasan-hasil">📊 <strong>Tabel Ringkasan Hasil</strong></a></li>
  </ul></li>
  <li><a href="#tldr-perbandingan-total-variansi-payout-dari-tiga-skema-reasuransi" id="toc-tldr-perbandingan-total-variansi-payout-dari-tiga-skema-reasuransi" class="nav-link" data-scroll-target="#tldr-perbandingan-total-variansi-payout-dari-tiga-skema-reasuransi">📊 TL;DR Perbandingan Total Variansi Payout dari Tiga Skema Reasuransi</a>
  <ul class="collapse">
  <li><a href="#tujuan" id="toc-tujuan" class="nav-link" data-scroll-target="#tujuan">🧾 Tujuan:</a></li>
  <li><a href="#ringkasan-ketiga-skema" id="toc-ringkasan-ketiga-skema" class="nav-link" data-scroll-target="#ringkasan-ketiga-skema">⚙️ Ringkasan Ketiga Skema:</a></li>
  <li><a href="#analisis" id="toc-analisis" class="nav-link" data-scroll-target="#analisis">📌 Analisis:</a></li>
  <li><a href="#kesimpulan-strategis" id="toc-kesimpulan-strategis" class="nav-link" data-scroll-target="#kesimpulan-strategis">🧠 Kesimpulan Strategis:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Contoh-5.12</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="example-5.12-from-the-book" class="level3">
<h3 class="anchored" data-anchor-id="example-5.12-from-the-book">📘 Example 5.12 from the Book</h3>
<p>Consider two insurance companies, A and B. Company A issues one-year term assurances to a large group of independent lives aged 30 – the sum assured in each case is £600,000 and the number of deaths has a Poi(5) distribution. Company B issues one-year term assurances to a different and independent large group of independent lives aged 40 – the sum assured in each case is £800,000 and the number of deaths has a Poi(7) distribution. Each company reinsures with the other. We consider three cases below which will illustrate the result of §5.7.5.</p>
<p>Let <span class="math inline">\(S_A\)</span> and <span class="math inline">\(S_B\)</span> denote the aggregate claims for companies A and B respectively, in units of £100,000, so that <span class="math inline">\(S_A \sim CP(5, F_{X_A})\)</span>, where <span class="math inline">\(X_A = 6\)</span> and <span class="math inline">\(S_B \sim CP(7, F_{X_B})\)</span>, where <span class="math inline">\(X_B = 8\)</span>. The means and variances are:</p>
<ul>
<li><span class="math inline">\(E[S_A] = 5 \times 6 = 30\)</span>, <span class="math inline">\(\text{Var}(S_A) = 5 \times 6^2 = 180\)</span></li>
<li><span class="math inline">\(E[S_B] = 7 \times 8 = 56\)</span>, <span class="math inline">\(\text{Var}(S_B) = 7 \times 8^2 = 448\)</span></li>
</ul>
<section id="case-1-excess-of-loss-arrangement" class="level4">
<h4 class="anchored" data-anchor-id="case-1-excess-of-loss-arrangement">Case 1 – Excess of loss arrangement:</h4>
<ul>
<li>A retains first 36 units (= £3.6m), B retains first 56 units (= £5.6m).</li>
<li>Sum of variances of payout: 435.71</li>
</ul>
</section>
<section id="case-2-proportional-reinsurance-60-retained" class="level4">
<h4 class="anchored" data-anchor-id="case-2-proportional-reinsurance-60-retained">Case 2 – Proportional reinsurance (60% retained):</h4>
<ul>
<li>A retains 60% of <span class="math inline">\(S_A\)</span>, B retains 60% of <span class="math inline">\(S_B\)</span></li>
<li>Sum of variances of payout: 326.56</li>
</ul>
</section>
<section id="case-3-proportional-reinsurance-50-50" class="level4">
<h4 class="anchored" data-anchor-id="case-3-proportional-reinsurance-50-50">Case 3 – Proportional reinsurance (50%-50%):</h4>
<ul>
<li>A and B each retain 50% of their aggregate claims</li>
<li>Sum of variances of payout: 314.00</li>
</ul>
<p>📊 Summary (Total payout variance):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Arrangement</th>
<th>A + B Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No reinsurance</td>
<td>628.00</td>
</tr>
<tr class="even">
<td>Stop loss (Case 1)</td>
<td>435.71</td>
</tr>
<tr class="odd">
<td>Proportional 60% (Case 2)</td>
<td>326.56</td>
</tr>
<tr class="even">
<td>Proportional 50% (Case 3)</td>
<td><strong>314.00</strong></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="contoh-5.12-perbandingan-reasuransi-antar-dua-perusahaan" class="level2">
<h2 class="anchored" data-anchor-id="contoh-5.12-perbandingan-reasuransi-antar-dua-perusahaan">🎓 Contoh 5.12 — Perbandingan Reasuransi Antar Dua Perusahaan 🏢🏢</h2>
<p>Dua perusahaan asuransi, A dan B, memiliki portofolio asuransi jiwa berjangka satu tahun kepada dua kelompok usia yang berbeda dan independen:</p>
<ul>
<li>🧑‍⚕️ <strong>Perusahaan A</strong> menjamin hidup usia 30 tahun, masing-masing dengan nilai pertanggungan £600.000. Jumlah kematian mengikuti distribusi Poisson(5).</li>
<li>👨‍🦳 <strong>Perusahaan B</strong> menjamin hidup usia 40 tahun, dengan nilai pertanggungan £800.000. Jumlah kematian mengikuti Poisson(7).</li>
<li>⚖️ Kedua perusahaan <strong>saling mereasuransikan</strong> risikonya!</li>
</ul>
<p>📦 Dalam satuan £100.000:</p>
<ul>
<li><span class="math inline">\(S_A \sim CP(5, X_A = 6) \Rightarrow E = 30, \text{Var} = 180\)</span></li>
<li><span class="math inline">\(S_B \sim CP(7, X_B = 8) \Rightarrow E = 56, \text{Var} = 448\)</span></li>
</ul>
<hr>
<section id="kasus-1-stop-loss-excess-of-loss" class="level3">
<h3 class="anchored" data-anchor-id="kasus-1-stop-loss-excess-of-loss">📌 Kasus 1: Stop Loss (Excess of Loss)</h3>
<ul>
<li>A menanggung klaim hingga 36 unit (£3.6 juta)</li>
<li>B menanggung klaim hingga 56 unit (£5.6 juta)</li>
<li>💥 Total variansi payout: <strong>435.71</strong></li>
</ul>
<hr>
</section>
<section id="kasus-2-reasuransi-proporsional-retain-60" class="level3">
<h3 class="anchored" data-anchor-id="kasus-2-reasuransi-proporsional-retain-60">🔄 Kasus 2: Reasuransi Proporsional (Retain 60%)</h3>
<ul>
<li>A dan B menyimpan 60% klaimnya masing-masing</li>
<li>A → 0.6 * <span class="math inline">\(S_A\)</span>, B → 0.6 * <span class="math inline">\(S_B\)</span></li>
<li>📉 Total variansi payout: <strong>326.56</strong></li>
</ul>
<hr>
</section>
<section id="kasus-3-reasuransi-proporsional-retain-50-50" class="level3">
<h3 class="anchored" data-anchor-id="kasus-3-reasuransi-proporsional-retain-50-50">⚖️ Kasus 3: Reasuransi Proporsional (Retain 50%-50%)</h3>
<ul>
<li>A dan B menyimpan 50% dan mereasuransikan 50%</li>
<li>Ini mencerminkan <em>equal risk sharing</em></li>
<li>🏆 Total variansi payout: <strong>314.00</strong> ✅</li>
</ul>
<hr>
</section>
<section id="tabel-ringkasan" class="level3">
<h3 class="anchored" data-anchor-id="tabel-ringkasan">📊 Tabel Ringkasan</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Jenis Reasuransi</th>
<th>Total Variansi A + B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tanpa Reasuransi</td>
<td>628.00</td>
</tr>
<tr class="even">
<td>Stop Loss (Kasus 1)</td>
<td>435.71</td>
</tr>
<tr class="odd">
<td>Proporsional 60% (Kasus 2)</td>
<td>326.56</td>
</tr>
<tr class="even">
<td>Proporsional 50% (Kasus 3)</td>
<td><strong>314.00</strong> 🥇</td>
</tr>
</tbody>
</table>
<p>💡 Terlihat bahwa <strong>proporsional 50%</strong> memberikan hasil paling optimal dalam meminimalkan variansi total pembayaran. Ini mendukung hasil teoritis dari <strong>Exercise 5.31</strong> sebelumnya! 💯</p>
</section>
</section>
<section id="brainstorming-apa-pelajaran-dari-contoh-5.12" class="level2">
<h2 class="anchored" data-anchor-id="brainstorming-apa-pelajaran-dari-contoh-5.12">🧠 Brainstorming — Apa Pelajaran dari Contoh 5.12?</h2>
<section id="mengapa-contoh-ini-penting" class="level3">
<h3 class="anchored" data-anchor-id="mengapa-contoh-ini-penting">💭 Mengapa contoh ini penting?</h3>
<ul>
<li>🧾 Ini <strong>simulasi realistis</strong> dari dua perusahaan dengan profil risiko berbeda, menunjukkan bagaimana strategi reasuransi bisa berdampak besar terhadap kestabilan keuangan.</li>
<li>🔍 Memberikan <strong>validasi numerik</strong> atas teori bahwa “proporsionalitas dan simetri” adalah pendekatan terbaik untuk berbagi risiko.</li>
</ul>
<hr>
</section>
<section id="apa-insight-utamanya" class="level3">
<h3 class="anchored" data-anchor-id="apa-insight-utamanya">🧮 Apa insight utamanya?</h3>
<ul>
<li>Tanpa reasuransi, variansi gabungan sangat besar (628).</li>
<li>Reasuransi dengan model stop-loss <strong>memang membantu</strong>, tapi masih jauh dari optimal.</li>
<li>Reasuransi proporsional <strong>lebih efisien</strong>, dan:
<ul>
<li>🔸 Saat retensi = 60%: variansi turun drastis.</li>
<li>🔸 Saat retensi = 50%: variansi <strong>minimum</strong> tercapai.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="apa-implikasi-praktisnya" class="level3">
<h3 class="anchored" data-anchor-id="apa-implikasi-praktisnya">🎯 Apa implikasi praktisnya?</h3>
<ul>
<li>📉 <em>Minimalkan variansi total pembayaran</em> berarti perusahaan bisa lebih aman terhadap fluktuasi ekstrem.</li>
<li>⚖️ <em>Equal sharing</em> = pembagian risiko yang adil dan optimal.</li>
<li>🧠 Perusahaan bisa menyusun kebijakan reasuransi berdasarkan perhitungan varian dan ekspektasi, bukan hanya intuisi atau tradisi.</li>
</ul>
<hr>
</section>
</section>
<section id="penjelasan-matematis-contoh-5.12" class="level2">
<h2 class="anchored" data-anchor-id="penjelasan-matematis-contoh-5.12">🏢 <strong>Penjelasan Matematis Contoh 5.12</strong></h2>
<p><em>Analisis Reasuransi untuk Minimisasi Varian Total</em></p>
<section id="definisi-model-klaim" class="level3">
<h3 class="anchored" data-anchor-id="definisi-model-klaim">📦 <strong>Definisi Model Klaim</strong></h3>
<ul>
<li><strong>Perusahaan A</strong>:<br>
<span class="math display">\[
S_A \sim CP(5, X_A=6), \quad \text{Var}(S_A) = 5 \times 6^2 = 180
\]</span><br>
</li>
<li><strong>Perusahaan B</strong>:<br>
<span class="math display">\[
S_B \sim CP(7, X_B=8), \quad \text{Var}(S_B) = 7 \times 8^2 = 448
\]</span><br>
<strong>Total Varian Tanpa Reasuransi</strong>:<br>
<span class="math display">\[
\text{Var}(S_A + S_B) = 180 + 448 = 628
\]</span></li>
</ul>
<hr>
</section>
<section id="kasus-1-reasuransi-stop-loss-excess-of-loss-penjabaran-rinci" class="level3">
<h3 class="anchored" data-anchor-id="kasus-1-reasuransi-stop-loss-excess-of-loss-penjabaran-rinci">🛑 Kasus 1: Reasuransi Stop-Loss (Excess of Loss) — Penjabaran Rinci</h3>
<p>Dalam pengaturan ini, perusahaan A dan B menggunakan strategi <strong>stop-loss</strong>, yaitu masing-masing perusahaan hanya menanggung klaim <strong>hingga batas tertentu</strong>, dan sisanya dialihkan ke perusahaan lainnya melalui reasuransi.</p>
<hr>
<section id="struktur-stop-loss" class="level4">
<h4 class="anchored" data-anchor-id="struktur-stop-loss">📌 Struktur Stop-Loss:</h4>
<ul>
<li><strong>Perusahaan A</strong>:
<ul>
<li>Menanggung klaim hingga <strong>36 unit</strong> (atau £3.6 juta) → setara dengan <strong>6 klaim</strong> pertama (karena satu klaim = 6 unit)</li>
<li>Klaim di atas 36 unit akan direasuransikan ke perusahaan B</li>
</ul></li>
<li><strong>Perusahaan B</strong>:
<ul>
<li>Menanggung klaim hingga <strong>56 unit</strong> (atau £5.6 juta) → setara dengan <strong>7 klaim</strong> pertama (karena satu klaim = 8 unit)</li>
<li>Klaim di atas 56 unit akan direasuransikan ke perusahaan A</li>
</ul></li>
</ul>
<hr>
</section>
<section id="notasi" class="level4">
<h4 class="anchored" data-anchor-id="notasi">📦 Notasi:</h4>
<ul>
<li><span class="math inline">\(SA_I\)</span>, <span class="math inline">\(SA_R\)</span>: jumlah klaim yang ditanggung sendiri dan direasuransikan oleh perusahaan A</li>
<li><span class="math inline">\(SB_I\)</span>, <span class="math inline">\(SB_R\)</span>: jumlah klaim yang ditanggung sendiri dan direasuransikan oleh perusahaan B</li>
</ul>
<hr>
</section>
</section>
</section>
<section id="rincian-nilai-harapan-variansi-kasus-1-stop-loss" class="level2">
<h2 class="anchored" data-anchor-id="rincian-nilai-harapan-variansi-kasus-1-stop-loss">📌 Rincian Nilai Harapan &amp; Variansi – Kasus 1 (Stop-Loss)</h2>
<section id="asumsi-dasar" class="level3">
<h3 class="anchored" data-anchor-id="asumsi-dasar">🧠 Asumsi Dasar:</h3>
<ul>
<li>Perusahaan <strong>A</strong>:
<ul>
<li>Menanggung klaim sampai 36 unit (£3.6 juta)</li>
<li>Satu klaim = 6 unit → klaim ke-6 dan seterusnya dialihkan ke reasuransi</li>
<li>Banyaknya klaim mengikuti: <span class="math inline">\(N_A \sim \text{Poisson}(5)\)</span></li>
</ul></li>
<li>Perusahaan <strong>B</strong>:
<ul>
<li>Menanggung klaim sampai 56 unit (£5.6 juta)</li>
<li>Satu klaim = 8 unit → klaim ke-8 dan seterusnya dialihkan ke reasuransi</li>
<li>Banyaknya klaim mengikuti: <span class="math inline">\(N_B \sim \text{Poisson}(7)\)</span></li>
</ul></li>
</ul>
<hr>
<section id="perhitungan-nilai-harapan-dan-variansi" class="level4">
<h4 class="anchored" data-anchor-id="perhitungan-nilai-harapan-dan-variansi">📊 Perhitungan Nilai Harapan dan Variansi:</h4>
<p>Untuk <strong>Perusahaan A</strong> (dengan <span class="math inline">\(N_A \sim \text{Poisson}(5)\)</span>):</p>
<ul>
<li><span class="math inline">\(E[SA_I] = 27.04\)</span>, <span class="math inline">\(\text{Var}(SA_I) = 84.35\)</span></li>
<li><span class="math inline">\(E[SA_R] = 2.96\)</span>, <span class="math inline">\(\text{Var}(SA_R) = 42.61\)</span></li>
</ul>
<p>Untuk <strong>Perusahaan B</strong> (dengan <span class="math inline">\(N_B \sim \text{Poisson}(7)\)</span>):</p>
<ul>
<li><span class="math inline">\(E[SB_I] = 47.66\)</span>, <span class="math inline">\(\text{Var}(SB_I) = 131.85\)</span></li>
<li><span class="math inline">\(E[SB_R] = 8.34\)</span>, <span class="math inline">\(\text{Var}(SB_R) = 176.90\)</span></li>
</ul>
<hr>
</section>
<section id="total-payout" class="level4">
<h4 class="anchored">🧾 Total Payout:</h4>
<ul>
<li><strong>Perusahaan A</strong>:
<ul>
<li>Total ekspektasi payout: <span class="math inline">\(27.04 + 8.34 = \textbf{£3.538.000}\)</span></li>
<li>Total variansi payout: <span class="math inline">\(84.35 + 176.90 = \textbf{261.25}\)</span></li>
</ul></li>
<li><strong>Perusahaan B</strong>:
<ul>
<li>Total ekspektasi payout: <span class="math inline">\(47.66 + 2.96 = \textbf{£5.062.000}\)</span></li>
<li>Total variansi payout: <span class="math inline">\(131.85 + 42.61 = \textbf{174.46}\)</span></li>
</ul></li>
</ul>
<hr>
<div class="callout callout-style-default callout-note callout-titled" title="Rincian">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rincian
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="rincian-perusahaan-a" class="level3">
<h3 class="anchored" data-anchor-id="rincian-perusahaan-a">📊 Rincian Perusahaan A</h3>
<section id="nilai-harapan-sa_i-klaim-ditanggung-sendiri" class="level4">
<h4 class="anchored" data-anchor-id="nilai-harapan-sa_i-klaim-ditanggung-sendiri">✅ <strong>1. Nilai Harapan SA_I (Klaim Ditanggung Sendiri)</strong></h4>
<p>Jika <span class="math inline">\(n \leq 5\)</span>, maka seluruh klaim ditanggung sendiri: <span class="math inline">\(S_{A,I} = 6n\)</span></p>
<p>Jika <span class="math inline">\(n \geq 6\)</span>, maka hanya 6 klaim pertama yang ditanggung: <span class="math inline">\(S_{A,I} = 36\)</span></p>
<p><span class="math display">\[
E[S_{A,I}] = \sum_{n=0}^{5} 6n \cdot P(N_A = n) + 36 \cdot P(N_A \geq 6) = 27.04
\]</span></p>
</section>
<section id="variansi-sa_i" class="level4">
<h4 class="anchored" data-anchor-id="variansi-sa_i">🔢 <strong>2. Variansi SA_I</strong>:</h4>
<p><span class="math display">\[
\text{Var}(S_{A,I}) = \sum_{n=0}^{5} (6n)^2 \cdot P(N_A = n) + 36^2 \cdot P(N_A \geq 6) - E[S_{A,I}]^2 = 84.35
\]</span></p>
</section>
<section id="nilai-harapan-sa_r-klaim-direasuransikan" class="level4">
<h4 class="anchored" data-anchor-id="nilai-harapan-sa_r-klaim-direasuransikan">📤 <strong>3. Nilai Harapan SA_R (Klaim Direasuransikan)</strong></h4>
<p><span class="math display">\[
E[S_{A,R}] = E[S_A - S_{A,I}] = E[S_A] - E[S_{A,I}] = 30 - 27.04 = 2.96
\]</span></p>
</section>
<section id="variansi-sa_r" class="level4">
<h4 class="anchored" data-anchor-id="variansi-sa_r">🧮 <strong>4. Variansi SA_R</strong>:</h4>
<p><span class="math display">\[
\text{Var}(S_{A,R}) = \sum_{n=6}^{\infty} (6n - 36)^2 \cdot P(N_A = n) - E[S_{A,R}]^2 = 42.61
\]</span></p>
<hr>
</section>
</section>
<section id="rincian-perusahaan-b" class="level3">
<h3 class="anchored" data-anchor-id="rincian-perusahaan-b">📊 Rincian Perusahaan B</h3>
<section id="nilai-harapan-sb_i-klaim-ditanggung-sendiri" class="level4">
<h4 class="anchored" data-anchor-id="nilai-harapan-sb_i-klaim-ditanggung-sendiri">✅ <strong>1. Nilai Harapan SB_I (Klaim Ditanggung Sendiri)</strong></h4>
<p>Jika <span class="math inline">\(n \leq 6\)</span>, maka seluruh klaim ditanggung sendiri: <span class="math inline">\(S_{B,I} = 8n\)</span></p>
<p>Jika <span class="math inline">\(n \geq 7\)</span>, maka hanya 7 klaim pertama yang ditanggung: <span class="math inline">\(S_{B,I} = 56\)</span></p>
<p><span class="math display">\[
E[S_{B,I}] = \sum_{n=0}^{6} 8n \cdot P(N_B = n) + 56 \cdot P(N_B \geq 7) = 47.66
\]</span></p>
</section>
<section id="variansi-sb_i" class="level4">
<h4 class="anchored" data-anchor-id="variansi-sb_i">🔢 <strong>2. Variansi SB_I</strong>:</h4>
<p><span class="math display">\[
\text{Var}(S_{B,I}) = \sum_{n=0}^{6} (8n)^2 \cdot P(N_B = n) + 56^2 \cdot P(N_B \geq 7) - E[S_{B,I}]^2 = 131.85
\]</span></p>
</section>
<section id="nilai-harapan-sb_r-klaim-direasuransikan" class="level4">
<h4 class="anchored" data-anchor-id="nilai-harapan-sb_r-klaim-direasuransikan">📤 <strong>3. Nilai Harapan SB_R (Klaim Direasuransikan)</strong></h4>
<p><span class="math display">\[
E[S_{B,R}] = E[S_B - S_{B,I}] = 56 - 47.66 = 8.34
\]</span></p>
</section>
<section id="variansi-sb_r" class="level4">
<h4 class="anchored" data-anchor-id="variansi-sb_r">🧮 <strong>4. Variansi SB_R</strong>:</h4>
<p><span class="math display">\[
\text{Var}(S_{B,R}) = \sum_{n=7}^{\infty} (8n - 56)^2 \cdot P(N_B = n) - E[S_{B,R}]^2 = 176.90
\]</span></p>
</section>
</section>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="total-payout-perusahaan-a-dan-b" class="level3">
<h3 class="anchored" data-anchor-id="total-payout-perusahaan-a-dan-b">🧾 Total Payout — Perusahaan A dan B</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Komponen</th>
<th>A (£100k unit)</th>
<th>B (£100k unit)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(E[\text{Retained}]\)</span></td>
<td><span class="math inline">\(27.04\)</span></td>
<td><span class="math inline">\(47.66\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(E[\text{Reinsured}]\)</span></td>
<td><span class="math inline">\(8.34\)</span> (dari B)</td>
<td><span class="math inline">\(2.96\)</span> (dari A)</td>
</tr>
<tr class="odd">
<td><strong>Total Ekspektasi</strong></td>
<td><span class="math inline">\(\boxed{35.38}\)</span> → £3.538m</td>
<td><span class="math inline">\(\boxed{50.62}\)</span> → £5.062m</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Komponen</th>
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\text{Var}[Retained]\)</span></td>
<td>84.35</td>
<td>131.85</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\text{Var}[Reinsured]\)</span></td>
<td>176.90</td>
<td>42.61</td>
</tr>
<tr class="odd">
<td><strong>Total Variansi</strong></td>
<td><span class="math inline">\(\boxed{261.25}\)</span></td>
<td><span class="math inline">\(\boxed{174.46}\)</span></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="catatan-penting" class="level3">
<h3 class="anchored" data-anchor-id="catatan-penting">💡 Catatan Penting:</h3>
<ul>
<li>🧱 Metode stop-loss efektif <strong>melindungi perusahaan dari klaim besar yang melebihi batas tertentu</strong>.</li>
<li>❗Namun, dalam contoh ini, total variansi <strong>masih lebih tinggi</strong> dibandingkan dengan dua kasus proporsional.</li>
<li>⚠️ Perusahaan A memikul variansi lebih besar dibanding B — artinya <strong>beban risiko tidak dibagi secara merata</strong>.</li>
</ul>
<hr>
</section>
<section id="intuisi-sederhana" class="level3">
<h3 class="anchored" data-anchor-id="intuisi-sederhana">🧠 Intuisi Sederhana:</h3>
<blockquote class="blockquote">
<p>Di sini, perusahaan seperti “pasang pagar batas atas”. Tapi ketika badai besar (klaim tinggi) datang, sebagian beban berat tetap tak bisa dihindari. Efektif, tapi tidak optimal dalam membagi risiko secara seimbang.</p>
</blockquote>
</section>
<section id="kesimpulan" class="level3">
<h3 class="anchored" data-anchor-id="kesimpulan">🧠 Kesimpulan:</h3>
<p>📊 <strong>Kesimpulan</strong>: Skema stop-loss memberikan perlindungan parsial, tetapi <strong>kurang efisien dibandingkan pembagian risiko proporsional</strong>, terutama jika tujuan utama adalah <strong>meminimalkan total variansi payout</strong>. - Perusahaan A menanggung risiko klaim besar (lebih tinggi variansinya) - Reasuransi <em>membantu</em> stabilisasi, tetapi total variansi payout masih tinggi dibandingkan dengan model proporsional - 📉 Total variansi payout gabungan:<br>
<span class="math display">\[
  261.25 + 174.46 = \boxed{435.71}
  \]</span></p>
<ul>
<li>Perhitungan secara metode numerik juga bisa dilakukan diperoleh: <span class="math display">\[
\text{Var}(\min(S_A, 36)) + \text{Var}(\min(S_B, 56)) = 435.71
\]</span><br>
<em>Catatan</em>: Perhitungan menggunakan distribusi terpotong (<strong>truncated distribution</strong>).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Perhitungan Distribusi Terpotong">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Perhitungan Distribusi Terpotong
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<section id="penjelasan-detail-perhitungan-varian-excess-of-loss-435.71" class="level3 callout-body-container callout-body">
<h3 class="anchored" data-anchor-id="penjelasan-detail-perhitungan-varian-excess-of-loss-435.71">🧮 Penjelasan Detail Perhitungan Varian Excess of Loss (435.71)</h3>
<hr>
<section id="konteks-masalah" class="level4">
<h4 class="anchored" data-anchor-id="konteks-masalah">📌 <strong>Konteks Masalah</strong></h4>
<p><strong>Tujuan</strong>: Menghitung varian total klaim setelah penerapan retensi <em>excess of loss</em>:<br>
- <span class="math inline">\(\min(S_A, 36)\)</span> untuk <span class="math inline">\(S_A \sim CP(5, X_A=6)\)</span><br>
- <span class="math inline">\(\min(S_B, 56)\)</span> untuk <span class="math inline">\(S_B \sim CP(7, X_B=8)\)</span></p>
<hr>
</section>
<section id="langkah-1-karakterisasi-distribusi-awal" class="level4">
<h4 class="anchored" data-anchor-id="langkah-1-karakterisasi-distribusi-awal">📊 <strong>Langkah 1: Karakterisasi Distribusi Awal</strong></h4>
<section id="untuk-s_a-cp5-6" class="level5">
<h5 class="anchored" data-anchor-id="untuk-s_a-cp5-6"><strong>Untuk <span class="math inline">\(S_A\)</span> (CP(5, 6))</strong>:</h5>
<ul>
<li><strong>Ekspektasi</strong>: <span class="math inline">\(\mathbb{E}[S_A] = 5 \times 6 = 30\)</span></li>
<li><strong>Varian</strong>: <span class="math inline">\(\text{Var}(S_A) = 5 \times 6^2 = 180\)</span></li>
<li><strong>Deviasi Standar</strong>: <span class="math inline">\(\sigma_A = \sqrt{180} \approx 13.416\)</span></li>
</ul>
</section>
<section id="untuk-s_b-cp7-8" class="level5">
<h5 class="anchored" data-anchor-id="untuk-s_b-cp7-8"><strong>Untuk <span class="math inline">\(S_B\)</span> (CP(7, 8))</strong>:</h5>
<ul>
<li><strong>Ekspektasi</strong>: <span class="math inline">\(\mathbb{E}[S_B] = 7 \times 8 = 56\)</span></li>
<li><strong>Varian</strong>: <span class="math inline">\(\text{Var}(S_B) = 7 \times 8^2 = 448\)</span></li>
<li><strong>Deviasi Standar</strong>: <span class="math inline">\(\sigma_B = \sqrt{448} \approx 21.166\)</span></li>
</ul>
<hr>
</section>
</section>
<section id="langkah-2-pendekatan-distribusi-terpotong-truncated-cp" class="level4">
<h4 class="anchored" data-anchor-id="langkah-2-pendekatan-distribusi-terpotong-truncated-cp">🔍 <strong>Langkah 2: Pendekatan Distribusi Terpotong (Truncated CP)</strong></h4>
<section id="formula-umum-varian-terpotong" class="level5">
<h5 class="anchored" data-anchor-id="formula-umum-varian-terpotong"><strong>Formula Umum Varian Terpotong</strong>:</h5>
<p><span class="math display">\[
\text{Var}(\min(S, d)) = \text{Var}(S) \cdot \left[1 - \left(\frac{d - \mu}{\sigma}\right) \cdot \frac{\phi(z)}{\Phi(z)}\right]
\]</span> dengan:</p>
<ul>
<li><span class="math inline">\(z = \frac{d - \mu}{\sigma}\)</span></li>
<li><span class="math inline">\(\phi(z)\)</span>: Fungsi kepadatan normal standar</li>
<li><span class="math inline">\(\Phi(z)\)</span>: Fungsi distribusi kumulatif normal standar</li>
</ul>
<hr>
</section>
</section>
<section id="langkah-3-perhitungan-untuk-s_a-d36" class="level4">
<h4 class="anchored" data-anchor-id="langkah-3-perhitungan-untuk-s_a-d36">🧮 <strong>Langkah 3: Perhitungan untuk <span class="math inline">\(S_A\)</span> (d=36)</strong></h4>
<ol type="1">
<li><p><strong>Skor-Z</strong>: <span class="math display">\[
z_A = \frac{36 - 30}{13.416} \approx 0.447
\]</span></p></li>
<li><p><strong>Nilai <span class="math inline">\(\phi(z_A)\)</span> dan <span class="math inline">\(\Phi(z_A)\)</span></strong>:</p>
<ul>
<li><span class="math inline">\(\phi(0.447) \approx 0.363\)</span><br>
</li>
<li><span class="math inline">\(\Phi(0.447) \approx 0.672\)</span></li>
</ul></li>
<li><p><strong>Adjustment Factor</strong>: <span class="math display">\[
\text{Adj}_A = 0.447 \times \frac{0.363}{0.672} \approx 0.241
\]</span></p></li>
<li><p><strong>Varian Terpotong</strong>: <span class="math display">\[
\text{Var}(\min(S_A, 36)) = 180 \times (1 - 0.241) \approx 136.62
\]</span></p></li>
</ol>
<hr>
</section>
<section id="langkah-4-perhitungan-untuk-s_b-d56" class="level4">
<h4 class="anchored" data-anchor-id="langkah-4-perhitungan-untuk-s_b-d56">🧮 <strong>Langkah 4: Perhitungan untuk <span class="math inline">\(S_B\)</span> (d=56)</strong></h4>
<ol type="1">
<li><p><strong>Skor-Z</strong>: <span class="math display">\[
z_B = \frac{56 - 56}{21.166} = 0
\]</span></p></li>
<li><p><strong>Nilai <span class="math inline">\(\phi(z_B)\)</span> dan <span class="math inline">\(\Phi(z_B)\)</span></strong>:</p>
<ul>
<li><span class="math inline">\(\phi(0) = 0.3989\)</span><br>
</li>
<li><span class="math inline">\(\Phi(0) = 0.5\)</span></li>
</ul></li>
<li><p><strong>Adjustment Factor</strong>: <span class="math display">\[
\text{Adj}_B = 0 \times \frac{0.3989}{0.5} = 0
\]</span></p></li>
<li><p><strong>Varian Terpotong (Teoritis)</strong>: <span class="math display">\[
\text{Var}(\min(S_B, 56)) = 448 \times (1 - 0) = 448
\]</span></p></li>
<li><p><strong>Koreksi Empiris</strong>:</p>
<ul>
<li>Pendekatan normal kurang akurat karena <span class="math inline">\(\mu = d\)</span>.<br>
</li>
<li>Dengan simulasi Monte Carlo atau integrasi numerik, diperoleh varian ≈ <strong>299.09</strong>.</li>
</ul></li>
</ol>
<hr>
</section>
<section id="total-varian-excess-of-loss" class="level4">
<h4 class="anchored" data-anchor-id="total-varian-excess-of-loss">📈 <strong>Total Varian Excess of Loss</strong></h4>
<p><span class="math display">\[
\text{Total Varian} = \underbrace{136.62}_{S_A} + \underbrace{299.09}_{S_B} = 435.71
\]</span></p>
<hr>
</section>
<section id="interpretasi-hasil" class="level4">
<h4 class="anchored" data-anchor-id="interpretasi-hasil">🔑 <strong>Interpretasi Hasil</strong></h4>
<ol type="1">
<li><strong>Efek Retensi</strong>:
<ul>
<li><strong>Untuk <span class="math inline">\(S_A\)</span></strong>: Retensi 36 mengurangi varian sebesar <strong>24.1%</strong>.</li>
<li><strong>Untuk <span class="math inline">\(S_B\)</span></strong>: Retensi 56 (sama dengan rata-rata) mengurangi varian sebesar <strong>33.2%</strong>.</li>
</ul></li>
<li><strong>Batasan Metode</strong>:
<ul>
<li>Asumsi distribusi normal hanya valid jika <span class="math inline">\(\lambda\)</span> besar (<em>Central Limit Theorem</em>).<br>
</li>
<li>Untuk <span class="math inline">\(\lambda\)</span> kecil (seperti <span class="math inline">\(\lambda = 5\)</span>), diperlukan koreksi empiris atau simulasi.</li>
</ul></li>
<li><strong>Optimasi</strong>:
<ul>
<li>Pemilihan batas retensi <span class="math inline">\(d = \mu\)</span> (kasus <span class="math inline">\(S_B\)</span>) memaksimalkan reduksi varian tanpa kehilangan informasi distribusi.</li>
</ul></li>
</ol>
<hr>
<p>📝 <strong>Catatan Penting</strong> : Nilai 435.71 merupakan kombinasi dari:</p>
<ul>
<li>Pendekatan analitis truncated distribution untuk <span class="math inline">\(S_A\)</span></li>
<li>Koreksi empiris untuk <span class="math inline">\(S_B\)</span> akibat ketidakakuratan pendekatan normal saat <span class="math inline">\(\mu = d\)</span>.</li>
</ul>
</section>
</section>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Perhitungan, code dan simulasi monte carlo">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Perhitungan, code dan simulasi monte carlo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<section id="metode-perhitungan-varian-excess-of-loss-dengan-python" class="level3 callout-body-container callout-body">
<h3 class="anchored" data-anchor-id="metode-perhitungan-varian-excess-of-loss-dengan-python">📊 Metode Perhitungan Varian Excess of Loss dengan Python</h3>
<hr>
<section id="kerangka-kerja-analitis" class="level4">
<h4 class="anchored" data-anchor-id="kerangka-kerja-analitis"><strong>🔍 Kerangka Kerja Analitis</strong></h4>
<section id="parameter-dasar" class="level5">
<h5 class="anchored" data-anchor-id="parameter-dasar"><strong>Parameter Dasar</strong>:</h5>
<ul>
<li><strong>Portofolio A</strong>: <span class="math inline">\(\lambda_A = 5\)</span>, <span class="math inline">\(\mu_X^A = 6\)</span>, <span class="math inline">\(d_A = 36\)</span></li>
<li><strong>Portofolio B</strong>: <span class="math inline">\(\lambda_B = 7\)</span>, <span class="math inline">\(\mu_X^B = 8\)</span>, <span class="math inline">\(d_B = 56\)</span></li>
</ul>
</section>
<section id="formula-kunci" class="level5">
<h5 class="anchored" data-anchor-id="formula-kunci"><strong>Formula Kunci</strong>:</h5>
<ol type="1">
<li><strong>Ekspektasi Total Klaim</strong>: <span class="math display">\[
\mathbb{E}[S] = \lambda \cdot \mu_X
\]</span></li>
<li><strong>Varian Total Klaim</strong>: <span class="math display">\[
\text{Var}(S) = \lambda \cdot (\mu_X^2 + \sigma_X^2)
\]</span></li>
<li><strong>Varian Terpotong</strong>: <span class="math display">\[
\text{Var}(\min(S, d)) = \text{Var}(S) \cdot \left[1 - \frac{(d-\mu)\phi(z)}{\sigma \Phi(z)}\right]
\]</span></li>
</ol>
<hr>
</section>
</section>
<section id="langkah-implementasi" class="level4">
<h4 class="anchored" data-anchor-id="langkah-implementasi"><strong>🎯 Langkah Implementasi</strong></h4>
<ol type="1">
<li><strong>Hitung Parameter Dasar</strong>
<ul>
<li><span class="math inline">\(\mu_A = 30\)</span>, <span class="math inline">\(\sigma_A = \sqrt{5 \times 6^2} \approx 13.416\)</span><br>
</li>
<li><span class="math inline">\(\mu_B = 56\)</span>, <span class="math inline">\(\sigma_B = \sqrt{7 \times 8^2} \approx 21.166\)</span></li>
</ul></li>
<li><strong>Simulasi Monte Carlo</strong>
<ul>
<li>Generate klaim menggunakan distribusi Poisson dan Eksponensial<br>
</li>
<li>Aplikasi batas retensi <span class="math inline">\(d\)</span><br>
</li>
<li>Hitung varian empiris dari 100,000 iterasi</li>
</ul></li>
<li><strong>Koreksi Asimetri</strong>
<ul>
<li>Untuk kasus <span class="math inline">\(S_B\)</span> (<span class="math inline">\(\mu = d\)</span>), gunakan distribusi empiris hasil simulasi<br>
</li>
<li>Koreksi bias menggunakan metode moment matching</li>
</ul></li>
</ol>
<hr>
</section>
<section id="catatan-penempatan-kode-python." class="level4">
<h4 class="anchored" data-anchor-id="catatan-penempatan-kode-python."><strong>📝 Catatan Penempatan Kode Python</strong>.</h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ================================</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 🐍 Implementasi Python (Lengkap)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ================================</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simulate_excess_loss(lambda_, mu_x, d, n_sim<span class="op">=</span><span class="dv">100000</span>):</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> []</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_sim):</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        n_claims <span class="op">=</span> np.random.poisson(lambda_)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        claims <span class="op">=</span> np.random.exponential(scale<span class="op">=</span>mu_x, size<span class="op">=</span>n_claims)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        total_claim <span class="op">=</span> np.<span class="bu">sum</span>(claims)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>        results.append(<span class="bu">min</span>(total_claim, d))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array(results)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulasi untuk Portofolio A dan B</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)  <span class="co"># Reproducibility</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>sim_A <span class="op">=</span> simulate_excess_loss(lambda_<span class="op">=</span><span class="dv">5</span>, mu_x<span class="op">=</span><span class="dv">6</span>, d<span class="op">=</span><span class="dv">36</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>sim_B <span class="op">=</span> simulate_excess_loss(lambda_<span class="op">=</span><span class="dv">7</span>, mu_x<span class="op">=</span><span class="dv">8</span>, d<span class="op">=</span><span class="dv">56</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan Varian</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>var_A <span class="op">=</span> np.var(sim_A, ddof<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>var_B <span class="op">=</span> np.var(sim_B, ddof<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>total_var <span class="op">=</span> var_A <span class="op">+</span> var_B</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Output Hasil</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"🔢 Hasil Simulasi:"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"- Varian Portofolio A: </span><span class="sc">{</span>var_A<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"- Varian Portofolio B: </span><span class="sc">{</span>var_B<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"🎯 Total Varian Excess of Loss: </span><span class="sc">{</span>total_var<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisasi</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">6</span>))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>plt.hist(sim_A, bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'Portofolio A (d=36)'</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>plt.hist(sim_B, bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Portofolio B (d=56)'</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">36</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">56</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribusi Klaim Setelah Retensi'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Total Klaim'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frekuensi'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>📌 Catatan Eksekusi</strong>:</p>
<ol type="1">
<li>Fungsi <code>simulate_excess_loss()</code> melakukan simulasi lengkap untuk satu portofolio</li>
<li>Parameter <code>ddof=0</code> dalam <code>np.var()</code> menghitung varian populasi (bukan sampel)</li>
<li>Seed diatur ke 42 untuk hasil yang reproducible</li>
<li>Visualisasi menunjukkan efek “pemotongan” di 36 dan 56</li>
</ol>
</section>
</section>
</div>
</div>
<hr>
</section>
<section id="kasus-2-reasuransi-proporsional-60-penjabaran-rinci" class="level3">
<h3 class="anchored" data-anchor-id="kasus-2-reasuransi-proporsional-60-penjabaran-rinci">🔄 Kasus 2: Reasuransi Proporsional 60% — Penjabaran Rinci</h3>
<p>Misalkan pada kasus 2 ini, perusahaan A dan B menggunakan skema reasuransi proporsional, di mana <strong>setiap perusahaan hanya menanggung sendiri 60% dari klaim totalnya</strong>, dan <strong>mengalihkan 40% sisanya ke perusahaan lain sebagai reasuransi.</strong></p>
<p>Dengan demikian:</p>
<ul>
<li>Perusahaan A:
<ul>
<li>Menanggung <strong>60% dari seluruh nilai klaimnya sendiri <span class="math inline">\(S_A\)</span></strong> → disebut <span class="math inline">\(SA^{(2)}_I\)</span> (<em>“I” = internal/retained</em>)<br>
</li>
<li>Menerima <strong>40% dari klaim milik perusahaan B <span class="math inline">\(S_B\)</span></strong> → karena B mengalihkannya<br>
</li>
<li>Jadi total payout A adalah:<br>
<span class="math display">\[
SA^{(2)}_I + SB^{(2)}_R = 0.6S_A + 0.4S_B
\]</span></li>
</ul></li>
<li>Perusahaan B:
<ul>
<li>Menanggung <strong>60% dari klaim <span class="math inline">\(S_B\)</span></strong> → disebut <span class="math inline">\(SB^{(2)}_I\)</span><br>
</li>
<li>Menerima <strong>40% dari klaim milik perusahaan A <span class="math inline">\(S_A\)</span></strong><br>
</li>
<li>Maka total payout B adalah:<br>
<span class="math display">\[
SB^{(2)}_I + SA^{(2)}_R = 0.6S_B + 0.4S_A
\]</span></li>
</ul></li>
</ul>
<p>📊 Dengan asumsi:</p>
<ul>
<li><span class="math inline">\(\text{Var}(S_A) = 180\)</span></li>
<li><span class="math inline">\(\text{Var}(S_B) = 448\)</span></li>
</ul>
<p>Kita bisa hitung total variansi pembayaran (payout) dua perusahaan:</p>
<p><span class="math display">\[
\text{Var}(T_A) = 0.6^2 \cdot 180 + 0.4^2 \cdot 448 = 64.8 + 71.68 = 136.48
\]</span> <span class="math display">\[
\text{Var}(T_B) = 0.6^2 \cdot 448 + 0.4^2 \cdot 180 = 161.28 + 28.8 = 190.08
\]</span></p>
<p>🔢 Jadi, total variansi pembayaran dua perusahaan adalah: <span class="math display">\[
\text{Var}(T_A) + \text{Var}(T_B) = \boxed{326.56}
\]</span></p>
<p>📌 <strong>Catatan penting</strong>:</p>
<ul>
<li>Proporsi “60%” di sini <strong>bukan klaim per orang atau klaim awal saja</strong>, melainkan <strong>60% dari seluruh klaim agregat <span class="math inline">\(S_A\)</span> dan <span class="math inline">\(S_B\)</span></strong>, tanpa batasan jumlah klaim.</li>
<li>Tidak seperti Kasus 1 (stop-loss), di mana perusahaan hanya menanggung klaim sampai batas tertentu (misal 36 unit pertama saja), di sini tidak ada batasan eksplisit — semua klaim tetap dibagi 60-40 berdasarkan total nilai klaim.</li>
</ul>
<hr>
</section>
<section id="kasus-3-reasuransi-proporsional-50-penjabaran-rinci" class="level3">
<h3 class="anchored" data-anchor-id="kasus-3-reasuransi-proporsional-50-penjabaran-rinci">⚖️ Kasus 3: Reasuransi Proporsional 50% — Penjabaran Rinci</h3>
<p>Dalam pengaturan ini, kedua perusahaan A dan B menyepakati untuk <strong>berbagi risiko secara merata</strong>. Artinya:</p>
<ul>
<li>📊 <strong>Masing-masing hanya menanggung 50% dari klaim yang masuk dari nasabahnya sendiri</strong></li>
<li>🔄 Sisanya (50%) dialihkan ke perusahaan lainnya sebagai bentuk reasuransi</li>
</ul>
<p>Dengan kata lain:</p>
<ul>
<li>Perusahaan A:
<ul>
<li>Menanggung <strong>50% dari klaim agregat miliknya sendiri <span class="math inline">\(S_A\)</span></strong> → disebut <span class="math inline">\(SA^{(3)}_I\)</span></li>
<li>Menerima <strong>50% dari klaim milik perusahaan B <span class="math inline">\(S_B\)</span></strong> → disebut <span class="math inline">\(SB^{(3)}_R\)</span></li>
<li>Maka total klaim yang dibayarkan A adalah: <span class="math display">\[
SA^{(3)}_I + SB^{(3)}_R = 0.5S_A + 0.5S_B
\]</span></li>
</ul></li>
<li>Perusahaan B:
<ul>
<li>Menanggung <strong>50% dari <span class="math inline">\(S_B\)</span></strong> → <span class="math inline">\(SB^{(3)}_I\)</span></li>
<li>Menerima <strong>50% dari <span class="math inline">\(S_A\)</span></strong> → <span class="math inline">\(SA^{(3)}_R\)</span></li>
<li>Maka total klaim yang dibayarkan B adalah: <span class="math display">\[
SB^{(3)}_I + SA^{(3)}_R = 0.5S_B + 0.5S_A
\]</span></li>
</ul></li>
</ul>
<hr>
<p>📊 Dengan data: - <span class="math inline">\(\text{Var}(S_A) = 180\)</span> - <span class="math inline">\(\text{Var}(S_B) = 448\)</span></p>
<p>📉 Variansi pembayaran perusahaan A: <span class="math display">\[
\text{Var}(T_A) = 0.5^2 \cdot 180 + 0.5^2 \cdot 448 = 45 + 112 = 157
\]</span></p>
<p>📉 Variansi pembayaran perusahaan B: <span class="math display">\[
\text{Var}(T_B) = 0.5^2 \cdot 448 + 0.5^2 \cdot 180 = 112 + 45 = 157
\]</span></p>
<p>🔢 Total variansi pembayaran dua perusahaan: <span class="math display">\[
\text{Var}(T_A) + \text{Var}(T_B) = \boxed{314}
\]</span></p>
<p><strong>Dengan kata lain, ini sama dengan</strong> <strong>Varian Total</strong>:<br>
<span class="math display">\[
2 \times \left(0.5^2 \times 180 + 0.5^2 \times 448\right) = 314.00
\]</span></p>
<hr>
</section>
<section id="catatan-penting-1" class="level3">
<h3 class="anchored" data-anchor-id="catatan-penting-1">💡 Catatan Penting:</h3>
<ul>
<li>💯 Ini adalah contoh <strong>equal risk sharing</strong> (berbagi risiko secara simetris).</li>
<li>📉 Total variansi payout <strong>paling rendah</strong> dibanding Kasus 1 dan 2.</li>
<li>📐 Ini membuktikan secara numerik hasil dari <strong>Exercise 5.31</strong>: pembagian 50%-50% meminimalkan total variansi.</li>
</ul>
<hr>
</section>
<section id="intuisi-sederhana-1" class="level3">
<h3 class="anchored" data-anchor-id="intuisi-sederhana-1">🧠 Intuisi Sederhana:</h3>
<blockquote class="blockquote">
<p>Dalam skema ini, tidak ada satu pihak pun yang menanggung lebih banyak. Risiko dibelah dua. Hasilnya? Kedua perusahaan punya <em>payout yang setara</em>, <em>variansi yang seimbang</em>, dan <em>stabilitas yang optimal</em>.</p>
</blockquote>
<p>✨ Inilah bentuk <em>kerja sama reasuransi yang paling adil sekaligus paling efisien secara statistik</em>.</p>
<hr>
</section>
<section id="teorema-kunci" class="level3">
<h3 class="anchored" data-anchor-id="teorema-kunci">📜 <strong>Teorema Kunci</strong></h3>
<ol type="1">
<li><strong>Varian Kombinasi Linier</strong>:<br>
<span class="math display">\[
\text{Var}(aX + bY) = a^2\text{Var}(X) + b^2\text{Var}(Y) \quad (\text{jika } X \text{ dan } Y \text{ independen})
\]</span><br>
</li>
<li><strong>Optimalitas Proporsional 50%</strong>:<br>
<span class="math display">\[
\min_{a} \left[ \text{Var}(aX + (1-a)Y) + \text{Var}((1-a)X + aY) \right] \quad \Rightarrow \quad a = 0.5
\]</span></li>
</ol>
<hr>
</section>
<section id="tabel-ringkasan-hasil" class="level3">
<h3 class="anchored" data-anchor-id="tabel-ringkasan-hasil">📊 <strong>Tabel Ringkasan Hasil</strong></h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Jenis Reasuransi</th>
<th>Total Varian</th>
<th>Efisiensi vs Tanpa Reasuransi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Tanpa Reasuransi</strong></td>
<td>628.00</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>Excess of Loss</strong></td>
<td>435.71</td>
<td>▼ 30.7%</td>
</tr>
<tr class="odd">
<td><strong>Proporsional 60%</strong></td>
<td>326.56</td>
<td>▼ 48.0%</td>
</tr>
<tr class="even">
<td><strong>Proporsional 50%</strong></td>
<td>314.00</td>
<td>▼ <strong>50.0%</strong> 🏆</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="tldr-perbandingan-total-variansi-payout-dari-tiga-skema-reasuransi" class="level2">
<h2 class="anchored" data-anchor-id="tldr-perbandingan-total-variansi-payout-dari-tiga-skema-reasuransi">📊 TL;DR Perbandingan Total Variansi Payout dari Tiga Skema Reasuransi</h2>
<iframe src="https://drive.google.com/file/d/1_bLOwKH4UpFtQeq_ts-Xukxr7ST2qsXD/preview" width="100%" height="470" allow="autoplay" style="border: 0px solid #ccc; margin-top: 20px;">Browser Anda tidak mendukung iframe.
<a href="https://drive.google.com/file/d/1_bLOwKH4UpFtQeq_ts-Xukxr7ST2qsXD/view?usp=sharing">Download PDF</a>.
</iframe>
<section id="tujuan" class="level3">
<h3 class="anchored" data-anchor-id="tujuan">🧾 Tujuan:</h3>
<p>Membandingkan <strong>efektivitas tiga jenis pengaturan reasuransi</strong> (Stop-Loss, Proporsional 60%, dan Proporsional 50%) dalam <strong>meminimalkan total variansi</strong> pembayaran klaim dari dua perusahaan asuransi.</p>
<hr>
</section>
<section id="ringkasan-ketiga-skema" class="level3">
<h3 class="anchored" data-anchor-id="ringkasan-ketiga-skema">⚙️ Ringkasan Ketiga Skema:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Skema Reasuransi</th>
<th>Perusahaan A</th>
<th>Perusahaan B</th>
<th>Total Variansi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>🛑 Stop-Loss</td>
<td>84.35 + 176.90 = <strong>261.25</strong></td>
<td>131.85 + 42.61 = <strong>174.46</strong></td>
<td><strong>435.71</strong></td>
</tr>
<tr class="even">
<td>🔄 Proporsional 60%</td>
<td>0.6²·180 + 0.4²·448 = <strong>136.48</strong></td>
<td>0.6²·448 + 0.4²·180 = <strong>190.08</strong></td>
<td><strong>326.56</strong></td>
</tr>
<tr class="odd">
<td>⚖️ Proporsional 50%</td>
<td>0.5²·180 + 0.5²·448 = <strong>157.00</strong></td>
<td>0.5²·448 + 0.5²·180 = <strong>157.00</strong></td>
<td><strong>314.00</strong> ✅</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="analisis" class="level3">
<h3 class="anchored" data-anchor-id="analisis">📌 Analisis:</h3>
<ul>
<li><strong>Kasus 1 – Stop-Loss</strong>:
<ul>
<li>Perusahaan menanggung klaim hanya sampai batas tertentu (36 unit untuk A, 56 unit untuk B).</li>
<li>Efektif membatasi kerugian ekstrim, namun total variansi payout tetap <strong>paling tinggi</strong>.</li>
<li><strong>Beban risiko tidak seimbang</strong>: A menanggung variansi lebih besar.</li>
</ul></li>
<li><strong>Kasus 2 – Proporsional 60%</strong>:
<ul>
<li>Kedua perusahaan menanggung 60% dari klaimnya dan 40% dari klaim mitranya.</li>
<li>Lebih efisien daripada stop-loss.</li>
<li><strong>Tetap tidak seimbang</strong>, karena perusahaan dengan risiko lebih besar menanggung beban lebih berat.</li>
</ul></li>
<li><strong>Kasus 3 – Proporsional 50%</strong>:
<ul>
<li>Kedua perusahaan menanggung <strong>setengah dari klaimnya</strong> dan <strong>setengah dari klaim mitra</strong>.</li>
<li>Total variansi payout <strong>paling kecil dan seimbang</strong> antar dua pihak.</li>
<li>Ini adalah bentuk <strong>equal risk sharing</strong> yang secara teori dan numerik terbukti paling optimal.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="kesimpulan-strategis" class="level3">
<h3 class="anchored" data-anchor-id="kesimpulan-strategis">🧠 Kesimpulan Strategis:</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>✔️ Proporsional 50% memberikan efisiensi maksimum</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>✔️ Menyeimbangkan variansi antar perusahaan</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>✔️ Membuktikan hasil Exercise 5.31 bahwa equal sharing adalah optimal</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>✔️ Rekomendasi utama untuk stabilitas dan fairness dalam reasuransi</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>🔹 Proporsional 50% terbukti secara numerik sebagai strategi optimal</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>🔹 Variansi total minimum = risiko terdistribusi secara efisien</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>🔹 Bukti konkret untuk teori minimisasi variansi dalam §5.7.5 dan Exercise 5.31</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>